export const ICON_CATEGORIES: Record<string, { name: string; icon: string }[]> = {
  Finance: [
    { name: "Wallet", icon: "wallet" },
    { name: "Money", icon: "money" },
    { name: "Bank", icon: "bank" },
    { name: "Credit Card", icon: "credit-card" },
    { name: "Coin", icon: "coin" },
    { name: "Coins", icon: "coins" },
    { name: "Currency Circle", icon: "currency-circle-dollar" },
    { name: "Trend Up", icon: "trend-up" },
    { name: "Trend Down", icon: "trend-down" },
    { name: "Chart Bar", icon: "chart-bar" },
    { name: "Chart Line", icon: "chart-line" },
    { name: "Chart Pie", icon: "chart-pie" },
    { name: "Receipt", icon: "receipt" },
    { name: "Calculator", icon: "calculator" },
    { name: "Percent", icon: "percent" },
  ],
  Food: [
    { name: "Fork Knife", icon: "fork-knife" },
    { name: "Coffee", icon: "coffee" },
    { name: "Beer", icon: "beer-stein" },
    { name: "Wine", icon: "wine" },
    { name: "Cake", icon: "cake" },
    { name: "Bowl Food", icon: "bowl-food" },
    { name: "Hamburger", icon: "hamburger" },
    { name: "Pizza", icon: "pizza" },
    { name: "Shopping Cart", icon: "shopping-cart" },
    { name: "Basket", icon: "basket" },
  ],
  Transport: [
    { name: "Car", icon: "car" },
    { name: "Car Simple", icon: "car-simple" },
    { name: "Bus", icon: "bus" },
    { name: "Train", icon: "train" },
    { name: "Airplane", icon: "airplane" },
    { name: "Bicycle", icon: "bicycle" },
    { name: "Motorcycle", icon: "motorcycle" },
    { name: "Gas Pump", icon: "gas-pump" },
    { name: "Road", icon: "road" },
  ],
  Shopping: [
    { name: "Shopping Bag", icon: "shopping-bag" },
    { name: "Shopping Cart", icon: "shopping-cart" },
    { name: "Tag", icon: "tag" },
    { name: "Gift", icon: "gift" },
    { name: "Backpack", icon: "backpack" },
    { name: "Tote", icon: "tote" },
    { name: "Storefront", icon: "storefront" },
  ],
  Health: [
    { name: "Heart", icon: "heart" },
    { name: "Heartbeat", icon: "heartbeat" },
    { name: "First Aid", icon: "first-aid" },
    { name: "Pill", icon: "pill" },
    { name: "Syringe", icon: "syringe" },
    { name: "Hospital", icon: "hospital" },
    { name: "Activity", icon: "activity" },
    { name: "Fork Knife", icon: "apple-logo" },
    { name: "Gym", icon: "dumbbell" },
  ],
  Education: [
    { name: "Book", icon: "book" },
    { name: "Books", icon: "books" },
    { name: "Book Open", icon: "book-open" },
    { name: "Graduation Cap", icon: "graduation-cap" },
    { name: "Student", icon: "student" },
    { name: "Pencil", icon: "pencil" },
    { name: "Pen", icon: "pen" },
    { name: "Lightbulb", icon: "lightbulb" },
    { name: "Globe", icon: "globe" },
  ],
  Entertainment: [
    { name: "Film Slate", icon: "film-slate" },
    { name: "Play", icon: "play" },
    { name: "Music Note", icon: "music-note" },
    { name: "Headphones", icon: "headphones" },
    { name: "Game Controller", icon: "game-controller" },
    { name: "Ticket", icon: "ticket" },
    { name: "Camera", icon: "camera" },
    { name: "Television", icon: "television" },
    { name: "Speaker", icon: "speaker-high" },
  ],
  Home: [
    { name: "House", icon: "house" },
    { name: "House Line", icon: "house-line" },
    { name: "Lightning", icon: "lightning" },
    { name: "Drop", icon: "drop" },
    { name: "Wifi", icon: "wifi-high" },
    { name: "Smartphone", icon: "smartphone" },
    { name: "Desktop", icon: "desktop" },
    { name: "Key", icon: "key" },
    { name: "Lock", icon: "lock" },
    { name: "Trash", icon: "trash" },
  ],
  Communication: [
    { name: "Chat", icon: "chat" },
    { name: "Chat Circle", icon: "chat-circle" },
    { name: "Envelope", icon: "envelope" },
    { name: "Phone", icon: "phone" },
    { name: "Bell", icon: "bell" },
    { name: "Megaphone", icon: "megaphone" },
  ],
  Weather: [
    { name: "Sun", icon: "sun" },
    { name: "Moon", icon: "moon" },
    { name: "Cloud", icon: "cloud" },
    { name: "Cloud Rain", icon: "cloud-rain" },
    { name: "Snowflake", icon: "snowflake" },
    { name: "Umbrella", icon: "umbrella" },
  ],
  Misc: [
    { name: "Star", icon: "star" },
    { name: "Heart", icon: "heart" },
    { name: "Flag", icon: "flag" },
    { name: "Fire", icon: "fire" },
    { name: "Crown", icon: "crown" },
    { name: "Diamond", icon: "diamond" },
    { name: "Rocket", icon: "rocket" },
    { name: "Behance", icon: "hand-waving" },
    { name: "Smiley", icon: "smiley" },
    { name: "Target", icon: "crosshair" },
    { name: "Compass", icon: "compass" },
  ],
}

export const ALL_ICONS = Object.entries(ICON_CATEGORIES).flatMap(([category, icons]) =>
  icons.map((i) => ({ ...i, category }))
)

export function getIconComponent(iconName?: string): string | null {
  if (!iconName) return null
  return ALL_ICONS.find((i) => i.icon === iconName)?.icon || null
}
